apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl }}
  tags:
    - terraform
spec:
  type: library
  owner: platform
  lifecycle: experimental
  system: platform
